#!/usr/bin/env bash
sudo apt update
sudo apt full-upgrade
sudo apt install --yes \
   emacs \
   gcc \
   git \
   gramps \
   graphviz \
   hledger \
   libgraphviz-dev \
   libimage-exiftool-perl \
   libxcb-xinerama0 \
   mit-scheme \
   mit-scheme-dbg \
   mit-scheme-doc \
   neovim \
   plocate \
   python-is-python3 \
   python3 \
   python3-dev \
   python3-tk \
   python3-venv \
   ripgrep \
   stockfish \

sudo git config --system core.editor emacs
sudo git config --system pull.rebase true

cd ~/Downloads
git clone https://github.com/adobe-fonts/source-sans.git
git clone https://github.com/adobe-fonts/source-code-pro.git
git clone https://github.com/adobe-fonts/source-serif.git
cd /usr/local/share/fonts
sudo mkdir opentype
cd opentype
sudo mkdir source-sans source-code-pro source-serif
sudo cp ~/Downloads/source-sans/OTF/*.otf source-sans
sudo cp ~/Downloads/source-code-pro/OTF/*.otf source-code-pro
sudo cp ~/Downloads/source-serif/OTF/*.otf source-serif
cd ~/Downloads
rm --force --recursive source-sans source-code-pro source-serif

echo -e '\nset editing-mode vi' | sudo tee --append /etc/inputrc
wget --output-document=- https://raw.githubusercontent.com/JohnADawson/setup/master/xkb/xkb-add-dawson | bash
sed --in-place 's/^HISTFILESIZE=[0-9]\+$/HISTFILESIZE=65536/' ~/.bashrc
git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
