#!/usr/bin/env bash
sudo apt update
sudo apt full-upgrade
sudo apt install --yes \
   anki \
   emacs \
   gcc \
   git \
   gnome-shell-pomodoro \
   gramps \
   graphviz \
   libgraphviz-dev \
   libimage-exiftool-perl \
   mit-scheme \
   mit-scheme-dbg \
   mit-scheme-doc \
   neovim \
   plocate \
   python3 \
   python3-dev \
   python3-tk \
   python3-venv \
   ripgrep \
   zathura \
   zathura-djvu \
   zathura-ps

sudo git config --system core.editor emacs
sudo git config --system pull.rebase true

cd /usr/local/share/fonts
sudo mkdir opentype
cd opentype
sudo mkdir source-sans source-code-pro source-serif
cd ~/Downloads
git clone https://github.com/adobe-fonts/source-sans.git
sudo cp source-sans/OTF/*.otf /usr/local/share/fonts/opentype/source-sans
git clone https://github.com/adobe-fonts/source-code-pro.git
sudo cp source-code-pro/OTF/*.otf /usr/local/share/fonts/opentype/source-code-pro
git clone https://github.com/adobe-fonts/source-serif.git
sudo cp source-serif/OTF/*.otf /usr/local/share/fonts/opentype/source-serif
rm --force --recursive source-sans source-code-pro source-serif

echo -e '\nset editing-mode vi' | sudo tee --append /etc/inputrc
wget --output-document=- https://raw.githubusercontent.com/JohnADawson/setup/master/xkb/xkb-add-dawson | bash
sed --in-place 's/^HISTFILESIZE=[0-9]\+$/HISTFILESIZE=65536/' ~/.bashrc
git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
