target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
  "ANN",
  "ARG",
  "DTZ",
  "EM",
  "INP",
  "T20",
  "B006",
  "B008",
  "COM812",
  "D203",
  "D213",
  "D413",
  "N806",
  "PLR2004",
  "PTH123",
  "SIM300",
]
